server:
  port: 8010

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: nacos-demo
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000