server:
  port: 8010

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      datasource:
        ds:
          nacos:
            server-addr: 127.0.0.1:8848
            data-id: ${spring.application.name}-sentinel
            group-id: DEFAULT_GROUP
            rule-type: flow
      transport:
        dashboard: 127.0.0.1:8858
      eager: true
  application:
    name: nacos-demo
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000