spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: nm-oauth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848/
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://docker.baostorm.com:3306/testdb?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: bx123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resource:
        user-info-uri: http://localhost:5000/user/current/get
        id: nm-oauth

server:
  port: 5000

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml